steps:
  # Build Laravel application image for Cloud Run
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/laravel-app:$SHORT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/laravel-app:latest'
      - '-f'
      - 'Dockerfile.cloudrun'
      - '.'
    id: 'build-app'

  # Push image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/laravel-app:$SHORT_SHA'
    id: 'push-sha'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/laravel-app:latest'
    id: 'push-latest'

  # Deploy to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'laravel-app'
      - '--image=gcr.io/$PROJECT_ID/laravel-app:$SHORT_SHA'
      - '--region=asia-northeast1'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--port=8080'
      - '--memory=1Gi'
      - '--cpu=2'
      - '--max-instances=10'
      - '--min-instances=0'
      - '--set-env-vars=APP_ENV=production'
      - '--set-env-vars=APP_DEBUG=false'
      - '--set-env-vars=LOG_CHANNEL=stderr'
    id: 'deploy-cloudrun'
    waitFor: ['push-sha']

images:
  - 'gcr.io/$PROJECT_ID/laravel-app:$SHORT_SHA'
  - 'gcr.io/$PROJECT_ID/laravel-app:latest'

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'

timeout: '1200s'